### PR TITLE
Added `boolean` return values to type definitions

### PR DESCRIPTION
**Pull request by paplorinc**
* Added `boolean` return values to `equals`/`isEqual`, `isBefore`/`isAfter`
* Added `string` type to `toString`
* Formatted union types uniformly

### CODE REVIEW

**Comment by pithu** [comment]
Hello @paplorinc 

thx for contributing again. Did you check the corresponding type definitions in the esdoc and fix it there as well ?

Its because we want the esdoc to be the leading source for type definitions. In an ideal world we would generate  typescript ( and flow, ...) definitions from the esdoc

**Comment by paplorinc** [comment]
Thanks @pithu, could you help me out with how I should go about doing that? :)

**Comment by pithu** [comment]
eg. For your fix https://github.com/js-joda/js-joda/pull/159/files#diff-e243a30e5201f226a48a91f2961294fbR53 find the corresponding esdoc type definition for DayOfWeek.isSupported  here https://github.com/js-joda/js-joda/blob/master/src/DayOfWeek.js#L180. In that case the esdoc is already correct.

**Comment by paplorinc** [comment]
@pithu, thanks, checked all `esdoc` definitions and they were correct (though the type wasn't explicitly stated in all cases, just "`true` if this `false` if that")

**Pull request merged**
