### PR TITLE
add method params for #appendValue and #appendValueReduced

### LINKED ISSUE #286: Fix typescript definitions for DateTimeFormatterBuilder#appendValue and #appendValueReduced
Currently these are defined in `js-joda.d.ts` as no-arg methods

### PR DESCRIPTION
**Pull request by jonfreedman**
Fixes #286

### CODE REVIEW

**Comment by pithu** [comment]
Hello @jonfreedman 

thanks a lot for using js-joda and contributing. There is only a test missing, could you please add a test case for you changes here [test/typescript_defintions/js-joda-tests.ts](https://github.com/js-joda/js-joda/blob/master/test/typescript_defintions/js-joda-tests.ts)

Thanks Philipp

**Comment by jonfreedman** [comment]
@pithu sure, I will add one

**Comment by jonfreedman** [comment]
@pithu any chance you can merge this?

**Comment by pithu** [comment]
Is there still a test for `appendValue` and `SignStyle` missing, or do i overlook it ?

**Comment by jonfreedman** [comment]
Apologies - I didn't test those methods as I don't use them and I couldn't find any examples in the current codebase.  I know the first two examples work, I've created another couple based on https://stackoverflow.com/questions/30103167/jsr-310-parsing-seconds-fraction-with-variable-length but I am less confident they are correct.

**Pull request merged**
