### PR TITLE
Explicit callout of not supporting all of ISO8601

### PR DESCRIPTION
**Pull request by gjbianco**
While I understand why (and even agree with) js-joda doesn't fully support ISO8601, the README mentions ISO8601 11 times and never explicitly mentions that the full standard is not supported.

It also looks like I'm not the only one that's been hit by this either:

#249 , #254 , #240 , #181 

Eventually, it would be really beneficial to enumerate which parts of ISO8601 are or are not supported.

### CODE REVIEW

**Comment by pithu** [comment]
@phueper do you have an opinion ?

**Comment by gjbianco** [comment]
I think that formulation is still vague about what is _not_ supported. Personally, I think the most clear wording explicitly describes that not _all_ of ISO8601 is supported.

**Comment by phueper** [comment]
hmmm... i think maybe it's better to describe what we support instead of stating what we do not support? would that be possible? e. g. describing the formats that are supported out of the box...

**Comment by gjbianco** [comment]
@phueper Definitely, but I don't think there is an explicit enough term for the exact parts of ISO 8601 that js-joda supports.

**Comment by pithu** [comment]
Well as i mentioned above, the build in format/ parse functions do support `RFC 3339, section 5.6`, isn't that very explicit ?

**Comment by gjbianco** [comment]
"Note well". I can change it to just "note: ..." if you prefer.

https://en.wikipedia.org/wiki/Nota_bene

**Comment by pithu** [comment]
In my opinion, thats quite to much detail information at this prominent place, what about 
`based on the ISO calendar system, which is the de facto world calendar following the proleptic Gregorian rules.` instead of `based on the ISO8601 calendar.`. Might it make more clear

And then add the reference to `RFC 3339, section 5.6` to the according `format` and `parse` methods of `LocalDate`, etc.

**Comment by gjbianco** [comment]
The whole _point_ of this PR is to make it more clear that the library (intentionally) does not support all of ISO8601. It is apparently not clear _enough_ since there are at least 4 documented cases of developers running into this issue.

I do not want to bury this in the documentation. If somebody is looking for a library to support ISO8601, it should be prominent that this library only supports a subset. Even if that's likely all they need, it should be as clear as possible _before_ they start digging into particular function docs.

Also, I didn't even add "based on the ISO8601 calendar" -- it was part of the original README.

**Comment by pithu** [comment]
Find my changes in the fix, fill free to open the issue again if i missed something

**Pull request closed without merging**
