### PR TITLE
add module property for es builds to locale packages

### PR DESCRIPTION
**Pull request by cercatrice**
To fix issue [#595](https://github.com/js-joda/js-joda/issues/595) in the locale modules.

### CODE REVIEW

**Review by pithu — COMMENTED** [review]
Aren't these files generated ? Can you please update the template https://github.com/js-joda/js-joda/blob/main/packages/locale/utils/create_packages.js#L49 and regenerate the files.

**Comment by cercatrice** [comment]
@pithu - apologies, I didn't see the package template previously. Just updated the branch with the changes to the packageTemplate and regenerated files.

**Comment by pithu** [comment]
Thanks @cercatrice for contributing

**Comment by cercatrice** [comment]
@pithu my pleasure. 
Let me know when you plan on rebuilding the locale npm package: https://www.npmjs.com/package/@js-joda/locale_en-us. We are updating our code base to ES modules, and this is the final moving piece (hopefully!!).

**Comment by pithu** [comment]
done, please let me know if it's working for you

**Comment by cercatrice** [comment]
Apologies for the delay. It is working! Thank you!

**Pull request merged**
