### PR TITLE
Changes needed for js-joda-locale implementation

### PR DESCRIPTION
**Pull request by phueper**
These changes are needed for js-joda-locale implementation, e.g. to be able to override the unimplemented functions in the plugin, also export some needed classes

### CODE REVIEW

**Comment by pithu** [comment]
One thing after first sight: What about exporting some more public interfaces as requested in issue #150 like `Temporal`, `TemporalAmount`, `TemporalUnit`

**Comment by phueper** [comment]
Ah... good point... will check it

**Comment by pithu** [comment]
Should we even export all classes interfaces that are public in threeten?

**Comment by phueper** [comment]
yes, i think that makes sense... i will do another commit on this PR, exporting everything that is public in threeten and even more internal classes that *migh* be used by plugins

**Pull request merged**
