### PR TITLE
Added Romanian joda locale

### PR DESCRIPTION
**Pull request by cipacda**
Fixes #422 

Can this be published?

### CODE REVIEW

**Comment by cipacda** [comment]
Do we know whether this can be merged and released?

**Comment by phueper** [comment]
Hi @cipacda  

thanks for the PR and sorry for the late answer ... the PR looks good to  me, i will see that if i can merge and publish in the next few days

Regards, Pattrick

**Comment by cipacda** [comment]
That will be much appreciated if possible. Many thanks :)

**Comment by cipacda** [comment]
Ping :)

Can I help in any way with publishing this?

**Pull request merged**
