### PR TITLE
Implement OffsetTime and OffsetDateTime

### LINKED ISSUE #240: OffsetTime missing
Hi, 

Firstly thanks for js-joda! I would like to know if you have plans to implement OffsetTime? 

I found another ticket discussing OffsetDateTime https://github.com/js-joda/js-joda/issues/165 and with that one it seems to make sense that the functionality already exists. 

Thanks,
Henry

### PR DESCRIPTION
**Pull request by exoego**
Closes #240

Thanks for creating this repository.
Recently, I have an increased need for `OffsetTime` and `OffsetDateTime`, so I am trying to add them.

I used the below source files as reference implementation.

* src
  * https://github.com/ThreeTen/threetenbp/blob/800401d216666575853412a459f8e8a83af95709/src/main/java/org/threeten/bp/OffsetDateTime.java
  * https://github.com/ThreeTen/threetenbp/blob/800401d216666575853412a459f8e8a83af95709/src/main/java/org/threeten/bp/OffsetTime.java
* test
  * https://github.com/ThreeTen/threetenbp/blob/800401d216666575853412a459f8e8a83af95709/src/test/java/org/threeten/bp/TestOffsetDateTime.java
  * https://github.com/ThreeTen/threetenbp/blob/800401d216666575853412a459f8e8a83af95709/src/test/java/org/threeten/bp/TestOffsetTime.java

IIUC, their license (BSD-3) is compatible with this repository. 

Please be aware that some extensive test cases are really slow, so I added `this.timeout(50000);` to extend timeout.

### CODE REVIEW

**Comment by exoego** [comment]
Only the below 2 test cases (which seems unrelated to this change) are failing... any help 🤔 ?

```
@js-joda/core:   1) plugTest
@js-joda/core:        should not fail using the localDateConvenientPlugin:
@js-joda/core:      TypeError: Cannot read property 'prototype' of undefined
@js-joda/core:       at fn (test/plugTest_mochaOnly.js:17:26)
@js-joda/core:       at use (src/use.js:15:13)
@js-joda/core:       at Context.<anonymous> (test/plugTest_mochaOnly.js:26:9)
@js-joda/core:       at processImmediate (internal/timers.js:456:21)
@js-joda/core:   2) plugTest
@js-joda/core:        should use the previously added plugin:
@js-joda/core:      TypeError: date1_.isAfterOrEqual is not a function
@js-joda/core:       at Context.<anonymous> (test/plugTest_mochaOnly.js:38:23)
@js-joda/core:       at processImmediate (internal/timers.js:456:21)
```

**Comment by pithu** [comment]
Hi @exoego 

Thanks a lot for the amazing work, all in all it looks good to me.

The test failure is probably one of this annoying cycle dependency issues. I could fix it by running the plugin test first. You can give the following change in the package.json a try:
```
   ...
    "test": "NODE_ENV=test ./node_modules/.bin/mocha --timeout 5000 --require @babel/register ./test/*Test_mochaOnly.js ./test/*Test.js ./test/**/*Test.js ./test/**/**/*Test.js",
   ...
```

The extended test timeouts are a problem. As far as i remember we had a lot of issues with flaky travis builds, because of that. We solved that by not iterating over all cases as the the ThreeTen tests are doing. Not the best solution, but i don't have a better fix and i doubt that tests in that detail bring any value. 
We also added some "reduced" tests for the browser and test coverage runners, you can find examples by searching for the usage of `isBrowserTestRunner` and `isCoverageTestRunner`.
Would be good if you could reduce test time, currently i guess most test are running below 200ms on travis.

**Comment by exoego** [comment]
@pithu Thanks for guidance.
Tests are reordered and slow tests are reduced.

**Comment by pithu** [comment]
Cool, that's fast ! 

Could you try to increase test coverage? Coverage decrease with your PR and looking into coverage reports it looks like there are reasonable candidates for tests https://coveralls.io/builds/31846690, eg tests for methods `until`, `isSupported`, `atDate`. 
And it would be also nice to have coverage for the new functionality in `Instant` and `LocalDate`.

**Comment by exoego** [comment]
OK, I will add more tests to increase coverage.

**Comment by exoego** [comment]
Now, newly added classes are 100% branch covered !!

**Comment by pithu** [comment]
Great contribution, thanks a lot!

**Pull request merged**
