### PR TITLE
Add WIP Typescript definitions (#23)

### PR DESCRIPTION
**Pull request by spencerwi**
Creating a PR with my work so far on the `.d.ts` definitions for this lib. There's a _lot_ to this lib, and while I went off the ESDoc pages, it's hard to know if I got things right right (there are some places where the signatures don't quite match between ESDoc and code, and some classes are not ESDoc'd). A lot of the not-really-user-facing classes are also not documented.

### CODE REVIEW

**Comment by phueper** [comment]
Thanks a lot again @spencerwi !
I'm not much of an typescript expert ... but out of curiosity... is there any way we can use typescript to "verify" this file?
e.g. some kind of unit test or npm script that we could run that checks wether the definitions in this file match the class and function names that we define in the code?

I've seen that DefinitelyTyped also requires tests for the .d.ts files contributed (http://definitelytyped.org/guides/contributing.html) ... maybe something like that to verify the file?

**Comment by Guria** [comment]
Yeah. You can install typescript as dependency and write some tests in ts files.

**Comment by Guria** [comment]
There is no need to push typings in DefinetyleTyped if lib has own typings defined in package.json.

**Comment by phueper** [comment]
FYI since i don't know how to add something to an existing (not mine) PR, i will probably create a new PR from my branch https://github.com/phueper/js-joda/tree/typescript_definitions including @spencerwi s commit and test files and other modifications 

as soon as a PR is coming out of that branch it will probably obsolete/close this PR

**Comment by Guria** [comment]
Just keep it open. When you merge your pr, github will mark this one as merged too.

**Comment by spencerwi** [comment]
So....anything more you need me to do here?

**Comment by phueper** [comment]
No, currently not... unless you want to comment on the changes i did in my branch... any input is of course very much welcome

**Pull request merged**
